config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  root to: 'pages#home'

  get 'search', to: 'pages#search', as: 'search'
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  include PgSearch::Model
  multisearchable against: [:title, :syllabus]
  # pg_search_scope :global_search,
  #   against: [ :title, :syllabus ],
  #   associated_against: {
  #     director: [ :first_name, :last_name]
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title, :syllabus]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present? #if you insert anything in search bar
      #sql_query = "title ILIKE :query OR syllabus ILIKE :query"
      # sql_query = " \
      # movies.title ILIKE :query \
      # OR movies.syllabus ILIKE :query \
      # OR directors.first_name ILIKE :query \
      # OR directors.last_name ILIKE :query \
      # "
      # sql_query = " \
      # movies.title @@ :query \
      # OR movies.syllabus @@ :query \
      # OR directors.first_name @@ :query \
      # OR directors.last_name @@ :query \
      # "

      #@movies = Movie.where(title: params[:query])
      #@movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
      #@movies = Movie.where(sql_query, query: "%#{params[:query]}%")
      #@movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
      #@movies = Movie.global_search(params[:query])
      @movies = PgSearch.multisearch(params[:query])
      #SQL
    else
      @store = Store.all
      @products = Product.all
      @movies = Movie.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def search
    @tvshows = TvShow.all
    @movies = Movie.all
    if params[:query].present? #if you insert anything in search bar
      @results = PgSearch.multisearch(params[:query])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbSearch382</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div id="movies">
        <%= form_tag movies_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a Movie" %>
          <%= submit_tag "Go", class: "btn btn-primary" %>
        <% end %>
        <% @movies.each do |result| %>
          <h4><%= result.searchable.title %></h4>
          <p><%= result.searchable.syllabus %></p>
          <p>type: <%= result.searchable_type %></p>

        <% end %>
<!--         <%# @movies.each do |movie| %>
         <h4><%#= movie.title %></h4>
         <p><%#= movie.syllabus %></p>
         <%# end %> -->
      </div>
    </div>
  </div>
</div>

app/views/pages/_search_form.html.erb
<%= form_tag search_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
  placeholder: "Search the app" %>
  <%= submit_tag "Go", class: "btn btn-primary" %>
<% end %>

app/views/pages/_search_suggestions.html.erb
<div class="container">
  <h1>Here are Some Movies in our app</h1>
  <div class="row">
    <% @movies.all.sample(3).each do |movie| %>
    <div class="col">
      <div class="card">
        <h1><%= movie.title %></h1>
        <p><%= movie.syllabus %></p>
      </div>
    </div>
    <% end %>
    <div class="row">
      <% @tvshows.all.sample(3).each do |tvshow| %>
      <div class="col">
        <div class="card">
          <h1><%= tvshow.title %></h1>
          <p><%= tvshow.syllabus %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/search.html.erb
<h1>Search page</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <div id="search">
        <%= render 'search_form' %>
        <% if @results.present? %>
          <% @results.each do |result| %>
            <h4><%= result.searchable.title %></h4>
            <p><%= result.searchable.syllabus %></p>
            <p>type: <%= result.searchable_type %></p>
          <% end %>
        <% elsif !params[:query].present? %>
          <%= render 'search_suggestions' %>
        <% else %>
          <%= render 'search_suggestions' %>
         <% end %>
      </div>
    </div>
  </div>
</div>